- name: Playbook for git module examples
  hosts: aws
  gather_facts: false

  tasks:
  # git clone from github repo
  - name: git clone from Ansible Playbooks
    git:
      repo: 'https://github.com/shivamgupta-sg/html-assignment.git'
      dest: $HOME/git/
      clone: yes
      update: yes

# # Example read-write git checkout from github
# - git:
#     repo: ssh://git@github.com/mylogin/hello.git
#     dest: /home/mylogin/hello

  # ensuring the repo checkout exists
  - name: ensuring the repo checkout exists
    git:
      repo: 'https://github.com/shivamgupta-sg/html-assignment.git'
      dest: $HOME/srv/checkout/
      update: no

  # get information about the repository whether or not it has already been cloned locally.
  - name: get information about the repository
    git:
      repo: 'https://github.com/shivamgupta-sg/html-assignment.git'
      dest: $HOME/srv/checkout-2/
      clone: no
      update: no

  # # Example checkout a github repo and use refspec to fetch all pull requests
  # - git:
  #     repo: https://github.com/shivamgupta-sg/html-assignment.git
  #     dest: $HOME/src/ansible-examples
  #     refspec: '+refs/pull/*:refs/heads/*'

  # Example Create git archive from repo
  - git:
      repo: https://github.com/ansible/ansible-examples.git
      dest: $HOME/src/archive-example/
      archive: $HOME/src/ansible-examples.zip