- name: Playbook for git module examples
  hosts: aws
  gather_facts: false

  tasks:
  # git clone from github repo
  - name: git clone from Ansible Playbooks
    git:
      repo: 'https://github.com/shivamgupta-sg/html-assignment.git'
      dest: $HOME/git/
      clone: yes
      update: yes

  # ensuring the repo checkout exists
  - name: ensuring the repo checkout exists
    git:
      repo: 'https://github.com/shivamgupta-sg/html-assignment.git'
      dest: $HOME/srv/checkout/
      update: no

  # get information about the repository whether or not it has already been cloned locally.
  - name: get information about the repository
    git:
      repo: 'https://github.com/shivamgupta-sg/html-assignment.git'
      dest: $HOME/srv/checkout-2/
      clone: no
      update: no

  # Example Create git archive from repo
  - git:
      repo: https://github.com/ansible/ansible-examples.git
      dest: $HOME/src/archive-example/
      archive: $HOME/src/ansible-examples.zip