---
- name: Verify apache installation
  hosts: aws

  vars:
    http_port: 80
    max_clients: 200
  
  tasks:
  - name: Install Apache on Ubuntu Server
    apt:
      name: apache2 
      state: present
    become: yes
    notify:
    - Start apache

  handlers:
    - name: Start apache
      ansible.builtin.service:
        name: apache2
        state: started

    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted