---
- name: Playbook to understand loops
  hosts: localhost
  connection: local
  gather_facts: false

  vars: 
    numbers: [1, 2, 3, 4]

    intern:
      name: Shivam
      Department: DevOps

  tasks:
  # Looping through a list
  - name: Print the numbers list
    debug:
      msg: "{{ item }}"
    loop: "{{ numbers }}"

  # Loopoing through dictionary
  - name: Print the dictionary
    debug:
      msg: "{{ item }}"
    loop: "{{ intern | dict2items }}"
    
  # Looping through a range of values
  - name: Print the range (0-9)
    debug:
      msg: "{{ item }}"
    loop: "{{ range(10) | list }}"

  - name: Print the range (11-15)
    debug:
      msg: "{{ item }}"
    loop: "{{ range(11, 16) | list }}"

  - name: Print the range (1-20 spacing of 5)
    debug:
      msg: "{{ item }}"
    loop: "{{ range(0, 21, 5) | list }}"

  # Looping through inventory
  - name: Print all hosts
    debug:
      msg: "{{ item }}"
    loop: "{{ groups['all'] }}"
...